version: "3"
services:
  web:
    build: ./web
    image: gettingstarteddocker_web:latest
    volumes:
      - "./web/src:/var/www/portal"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  microservice:
    build: ./microservice
    image: gettingstarteddocker_microservice:latest
    volumes:
      - "./microservice:/microservice"
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - webnet
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - "/data/db/mongo:/data/db"
    tty: true
    networks:
      - webnet
networks:
  webnet:
